version: "3"

services:
    blog-backend:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: blog-backend
        depends_on:
            - mysql
        ports:
            - 8090:80
        volumes:
            - ./:/srv
            - ./apache2.conf:/etc/apache2/apache2.conf
            - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./php.ini:/usr/local/etc/php/php.ini

    mysql:
        image: mysql:8.0.19
        container_name: mysql
        ports:
            - 3336:3306
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog
        command: --default-authentication-plugin=mysql_native_password

    es:
        build:
            context: ./docker/elasticsearch
            dockerfile: Dockerfile
        container_name: blog-es
        ports:
          - 9200:9200
          - 9300:9300
        volumes:
            - es-data:/usr/share/elasticsearch/data
            - ./docker/elasticsearch/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml
            - ./docker/elasticsearch/my_stop_word.dic:/usr/share/elasticsearch/config/analysis-ik/my_stop_word.dic
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1

    kibana:
        image: kibana:7.7.0
        container_name: kibana
        depends_on:
            - es
        environment:
            - ELASTICSEARCH_HOSTS=http://es:9200
            - STATUS_ALLOWANONYMOUS=true
            - XPACK_SECURITY_ENABLED=false
        ports:
            - 5601:5601

volumes:
    mysql:
    es-data:
