version: "3"

services:
    blog-backend:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        container_name: blog-backend
        ports:
            - 8090:80
        volumes:
            - ./:/srv
            - ./apache2.conf:/etc/apache2/apache2.conf
            - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./php.ini:/usr/local/etc/php/php.ini

    mysql:
        image: mysql:8.0.19
        container_name: mysql
        ports:
            - 3336:3306
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql:
