# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Login to tencnet docker image registry
      run: echo "${{ secrets.TENCENT_REGISTRY_PASSWORD }}" |  docker login --username=100011753229 hkccr.ccs.tencentyun.com --password-stdin

    - name: Build image
      run: docker build . -t hkccr.ccs.tencentyun.com/qingfengbaili/blog-api --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --build-arg SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Push image to tencent docker image registry
      run: docker push hkccr.ccs.tencentyun.com/qingfengbaili/blog-api
